post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1paWtrYVJhdXRpbyIsImlkIjoiNjg5NWRlNTk2MzlkMjJiNDU3YTFmNGJkIiwiaWF0IjoxNzU0OTI1MzI1LCJleHAiOjE3NTQ5Mjg5MjV9.HN6s1gzyhNWV5gbLztgvRLDa9Ew0VbEcJZaFUiM9hiU


{
    "title": "Miikan kirja",
    "author": "sdfgsdfgs",
    "url": "entieda@jotain",
    "likes": 123
}


